export const mockData = [
  {
    category: "guitar",
    company: "SonicForge",
    name: "ThunderStrum",
    price: 249900,
    description:
      "Unleash the thunder with the ThunderStrum! This high-performance electric guitar is crafted for power and precision, delivering explosive riffs and searing solos.",
    colors: ["#000000", "#ff0000", "#ffffff"],
    featured: true,
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: true,
    inventory: 5,
    averageRating: 4.7,
    numOfReviews: 150,
  },
  {
    category: "guitar",
    company: "FretCrafted",
    name: "HarmonyHero",
    price: 189900,
    description:
      "Dive into musical harmony with the HarmonyHero. This handcrafted acoustic guitar resonates warmth and richness, creating melodies that captivate the soul.",
    colors: ["#8b4513", "#00ced1", "#f0e68c"],
    featured: true,
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: false,
    inventory: 8,
    averageRating: 4.2,
    numOfReviews: 80,
  },
  {
    category: "guitar",
    company: "AmpedArtistry",
    name: "BassBoom",
    price: 329900,
    description:
      "Feel the rumble with the BassBoom! This custom bass guitar delivers deep, punchy tones, perfect for laying down the foundation of your rhythm section.",
    colors: ["#2e8b57", "#9932cc", "#ffd700", "#00ced1"],
    featured: true,
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_3.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: true,
    inventory: 3,
    averageRating: 4.5,
    numOfReviews: 120,
  },
  {
    category: "guitar",
    company: "StrumCraft",
    name: "VintageVirtuoso",
    price: 279900,
    description:
      "Embrace the vintage vibe with the VintageVirtuoso. Meticulously restored, this classic guitar exudes timeless charm while delivering impeccable sound and playability.",
    colors: ["#8b4513", "#a0522d", "#00ced1"],
    featured: true,
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_4.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: false,
    inventory: 6,
    averageRating: 4.8,
    numOfReviews: 180,
  },
  {
    category: "guitar",
    company: "MetalizeGuitars",
    name: "ShredMaster",
    price: 269900,
    description:
      "Unleash the shredder within with the ShredMaster! This metal-style custom guitar is built for speed and precision, empowering you to dominate the stage.",
    colors: ["#000000", "#696969"],
    featured: true,
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_5.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: true,
    inventory: 4,
    averageRating: 4.6,
    numOfReviews: 90,
  },
  {
    category: "guitar",
    company: "SonicForge",
    name: "PhoenixFire",
    price: 299900,
    description:
      "Rise from the ashes with the PhoenixFire! This electric guitar ignites the stage with blazing tones, combining style and power for an unforgettable performance.",
    colors: ["#ff4500", "#ffd700", "#000000"],
    featured: true,
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_6.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: true,
    inventory: 7,
    averageRating: 4.9,
    numOfReviews: 220,
  },
  {
    category: "guitar",
    company: "FretCrafted",
    name: "SerenadeSculpt",
    price: 209900,
    description:
      "Crafted for enchanting melodies, the SerenadeSculpt acoustic guitar captivates with its sculpted design and harmonious resonance. Elevate your acoustic journey.",
    colors: ["#8b4513", "#ffffff"],
    featured: true,
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_7.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: false,
    inventory: 9,
    averageRating: 4.4,
    numOfReviews: 110,
  },
  {
    category: "guitar",
    company: "AmpedArtistry",
    name: "RhythmRover",
    price: 239900,
    description:
      "Navigate the rhythm landscape with the RhythmRover! This custom bass guitar offers a versatile sonic journey, ensuring a solid foundation for any musical expedition.",
    colors: ["#008000", "#4169e1", "#ffd700"],
    featured: true,
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_8.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: true,
    inventory: 5,
    averageRating: 4.6,
    numOfReviews: 130,
  },
  {
    category: "guitar",
    company: "StrumCraft",
    name: "HarmonicHue",
    price: 189900,
    description:
      "Dive into a symphony of color with the HarmonicHue. This vibrant acoustic guitar not only enchants the ears but also captivates the eyes with its stunning aesthetics.",
    colors: ["#ff69b4", "#32cd32", "#ffd700"],
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_9.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: false,
    inventory: 8,
    averageRating: 4.2,
    numOfReviews: 100,
  },
  {
    category: "guitar",
    company: "MetalizeGuitars",
    name: "RiffReaper",
    price: 259900,
    description:
      "Summon the heavy with the RiffReaper! This metal-style custom guitar is forged for earth-shattering riffs, ensuring your sonic presence dominates the metal realm.",
    colors: ["#000000", "#ff4500", "#696969"],
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_10.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: true,
    inventory: 6,
    averageRating: 4.7,
    numOfReviews: 160,
  },
  {
    category: "guitar",
    company: "SonicForge",
    name: "EclipseEcho",
    price: 309900,
    description:
      "Experience a sonic eclipse with the EclipseEcho! This electric guitar eclipses boundaries, delivering a fusion of power, precision, and ethereal resonance for an unparalleled performance.",
    colors: ["#000000", "#000080", "#ffffff"],
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_11.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: true,
    inventory: 4,
    averageRating: 4.8,
    numOfReviews: 190,
  },
  {
    category: "guitar",
    company: "FretCrafted",
    name: "MelodyMajesty",
    price: 229900,
    description:
      "Embrace the regal tones of the MelodyMajesty. This handcrafted acoustic guitar reigns with majestic sound, inviting you to orchestrate melodic symphonies with every strum.",
    colors: ["#8b4513", "#ffffff"],
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_12.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: false,
    inventory: 7,
    averageRating: 4.5,
    numOfReviews: 140,
  },
  {
    category: "guitar",
    company: "AmpedArtistry",
    name: "BassBlitz",
    price: 349900,
    description:
      "Ignite the bass revolution with the BassBlitz! This custom bass guitar unleashes a blitz of low-end thunder, ensuring your basslines resonate with unmatched power and precision.",
    colors: ["#2e8b57", "#9932cc", "#ffd700", "#20b2aa"],
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_13.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    freeShipping: true,
    inventory: 3,
    averageRating: 4.9,
    numOfReviews: 210,
  },
  {
    category: "guitar",
    company: "StrumCraft",
    name: "RetroResonance",
    price: 199900,
    description:
      "Revive the classics with the RetroResonance. This vintage-inspired guitar combines nostalgic design with modern playability, delivering timeless resonance for an authentic musical journey.",
    images: [
      "https://e-commerce-api-3xet.onrender.com/uploads/guitar_14.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-1.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-2.jpeg",
      "https://e-commerce-api-3xet.onrender.com/uploads/extra-product-3.jpeg",
    ],
    colors: ["#00ced1"],
    freeShipping: false,
    inventory: 9,
    averageRating: 4.3,
    numOfReviews: 120,
  },
];
